site_name: myloasm - metagenomic assembly with (noisy) long reads
site_url: https://myloasm-docs.github.io/
theme:
  name: material
  palette:
    primary: teal
  logo: assets/logo.svg


nav:
  - Introduction: index.md
  - Install : install.md
  - Quick usage: usage.md
  - Output:
    - Primary files: output.md
    - Secondary files: secondary.md
  - Mylotools - quality control and manipulation: 
    - Mylotools overview: mylotools.md
    - QC discussion: qc.md
    - Manual inspection with mylotools: qc_manual.md
  - Preliminary Results: results.md
  - Advanced info:
    - Full option reference: cmd.md
    - Changelog: CHANGELOG.md
  - Frequently asked questions: FAQ.md


markdown_extensions:
  - pymdownx.magiclink
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - autorefs


  
